# Generated by Django 3.0.8 on 2020-08-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Influencers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(blank=True, choices=[('Lifestyle', 'Lifestyle'), ('Food', 'Food'), ('Fashion', 'Fashion'), ('Artist', 'Artist'), ('Makeup', 'Makeup'), ('Mom', 'Mom'), ('Blogger', 'Blogger'), ('Travel', 'Travel'), ('Others', 'Others')], default='Others', max_length=30, null=True)),
                ('Others', models.CharField(max_length=100)),
            ],
        ),
    ]
