# Generated by Django 3.0.8 on 2020-08-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencers',
            name='Email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='influencers',
            name='FirstName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='influencers',
            name='Followers',
            field=models.CharField(choices=[('1k-5k', '1k-5k'), ('5k-10k', '5k-10k'), ('10k-20k', '10k-20k'), ('20k-50k', '20k-50k'), ('>50k', '>50k')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='influencers',
            name='LastName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='influencers',
            name='Mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='influencers',
            name='Username',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='influencers',
            name='Others',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
