# Generated by Django 3.0.8 on 2020-08-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200810_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=200, null=True)),
                ('LastName', models.CharField(max_length=200, null=True)),
                ('Email', models.EmailField(max_length=200, null=True)),
                ('Mobile', models.IntegerField(null=True)),
                ('BrandName', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
